### ISSUE TITLE
FR10. Show details of pet

### ISSUE THREAD

**Issue by drfrink** [WSU-4110/Pet-Finder#13]
|FR10. Show details of pet|
|---|
|**Goal**:  The system will show users the details of the pet once selected from a list of pets. |
|**Stakeholders:** End Users, Adoption Agencies|
| **Description:** When a pet is selected from the list of pets shown, the system will send the user to another page containing details of the pet such as the questionnaire results and adoption agency information.  |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2019| 
| **Priority:** 1 |

**Comment by alexkishekedu** [comment]
Finished the basics of the view pet page. I set up the page to display an image of the pet and have a description/qualities text next to the image. The user can also click on the button to view a list of adoption agencies as well. The front end is all done now I just need to fill in the data.

**Comment by alexkishekedu** [comment]
The page that displays the details of the pets along with a picture is complete.
