### ISSUE TITLE
FR11.  Fill out the questionnaire

### ISSUE THREAD

**Issue by Ali98Wayne** [WSU-4110/Pet-Finder#15]
|FR11.  Fill out the questionnaire|
|---|
|**Goal**: Website users can fill out a questionnaire to filter search their search results for pets in the database. |
|**Stakeholders:** End Users, Adoption Agencies|
| **Description:** This does not require an account to do this action. Users can select choices based on living conditions, wants, or personal preferences. Multiple questions will be asked to the user, the default selection will be “I don’t know” so that if they don’t have an answer for a specific question, they can leave that as the selection then move on. |
| **Origin:** From the original project proposal, the team leader suggested this feature. | 
| **Version:** 1.0 |  
|**Date:** 09/28/2020|
|  **Priority:** 1 |

**Comment by fx6041** [comment]
Rough html outline is made for the quiz. The quiz needs to be refined and the results still need a way to be sent to the personality algorithm. The functional requirement is to make sure that the quiz works properly when users are not logged in.

**Comment by fx6041** [comment]
The html, Models, and forms are all set up but i can not figure out how to send the choices to the server to process them

**Comment by fx6041** [comment]
choices made and connected to the database
