### ISSUE TITLE
NFR5.  Personal information is not fetched from users 

### ISSUE THREAD

**Issue by alexkishekedu** [WSU-4110/Pet-Finder#16]
|NFR5 Personal information is not fetched from users  |
|---|
|**Goal**: Ensure that only Agencies have their info saved to the database
**Stakeholders:** End Users, Adoption Agencies |
| **Description:**Any user who is not logged in will not have any personal information saved to our database. |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2020|  **Priority:** 3|

**Comment by Ali98Wayne** [comment]
Made sure the questionnaire didn't have personal information that the user could enter. As more questions are added we will keep this in mind.
