### ISSUE TITLE
FR12. Build the database for the app

### ISSUE THREAD

**Issue by Ali98Wayne** [WSU-4110/Pet-Finder#17]
|FR12.  Build the database for the app|
|---|
|**Goal**: The app needs a database to function properly so this will facilitate that
**Stakeholders:** End Users, Adoption Agencies|
| **Description:** The app needs a database to function properly so this will facilitate that. The Framework we are using has a built in database that can be utilized for this requirement.|
| **Origin:** An idea that was brought up when coming up with the Mockup UI from the first presentation.
| **Version:** 1.0 |  
|**Date:** 09/28/2020|  
|**Priority:** 2 |

**Comment by fx6041** [comment]
database completed able to view through the admin site.
