### ISSUE TITLE
FR6. Password reset function

### ISSUE THREAD

**Issue by drfrink** [WSU-4110/Pet-Finder#2]
|FR6. Password reset function|
|---|
|**Goal**: The system will allow the user to reset their password through email. |
|**Stakeholders:** Adoption Agencies|
| **Description:** When an adoption agency forgets their password to their account, they will need to be able to reset their password to log in. This page will allow them to reset their password by entering the email they have saved in their account profile. They can then reset their password within the provided email link.  |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2019| 
| **Priority:** 3 |

**Comment by alexkishekedu** [comment]
For this weeks sprint, I set up the routing and urls for the forgot user requirement. I also configured the basic layout of the html page for the forgot password where the user can enter an email with validated inputs and a submit button. My todo list for finishing this requirement would be to finish the backend code where the email sends and the user creates a new password.

**Comment by alexkishekedu** [comment]
Backend is now connected and password reset is functioning properly.
