### ISSUE TITLE
FR15.  Filter results based on the questionnaire

### ISSUE THREAD

**Issue by Ali98Wayne** [WSU-4110/Pet-Finder#20]
|FR15.  Filter results based on the questionnaire|
|---|
|**Goal**: When users fill out the questionnaire, there will be a filtering system to help display the correct results to them based on their answers. |
|**Stakeholders:** End Users, Adoption Agencies |
| **Description:** This filtering system will fetch pets from the database based on what the user filled out in the questionnaire. After the user clicks submit, multiple pets will be displayed on the screen with descriptions, tags, and the location of the pet. |
| **Origin:** From the original project proposal, filtering search results will be a major tool on this website. |
| **Version:** 1.0  |  
|**Date:** 09/28/2020 |
|  **Priority:** 2 |

**Comment by alexkishekedu** [comment]
Results now filter based on the questions that came from the quiz.
