### ISSUE TITLE
FR2.  Update the profile Page 

### ISSUE THREAD

**Issue by fx6041** [WSU-4110/Pet-Finder#3]
|FR2.  Update the profile Page|
|---|
|**Goal**: The system will let the adoption agency update their profile page with new information|
|**Stakeholders:** Customers|
| **Description:** When an adoption agency logs into their account they can navigate to their profile and update their profile with any new information that they may require. Such as a new location or updated contact Information. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2020|  **Priority:** 4 |

**Comment by Ali98Wayne** [comment]
Update Profile Page Template created (updProfile.html)

**Comment by Ali98Wayne** [comment]
Determined which information an Adoption Agency should have displayed on the Update Profile page (updProfile.html) (Name, Location, About Me, Contact, Profile Pic)

**Comment by Ali98Wayne** [comment]
Adoption Agencies should not upload their own profile pictures to the database, instead they can choose from a list of 5 preset pictures.

**Comment by Ali98Wayne** [comment]
Searched online and local files to see which photos can be used as Profile Icons for the Agency to select from.

**Comment by Ali98Wayne** [comment]
Tested what dimensions to give to the stock-esque images (100 x 100 when displayed in a list, 300 x 300 when displayed in the profile page). Meaning there would be 2 instances (2 files) for a profile icon.

**Comment by Ali98Wayne** [comment]
To prevent issues on devices with smaller screens, selecting a Profile Icon will be done on the bottom of the Update Profile page, instead of initially hoping to implement it on the top-left of the page.

**Comment by Ali98Wayne** [comment]
***For now, clicking on an image in the Update Profile page doesn't do anything, plans actually tie this into an Agency's account is in the works***

**Comment by Ali98Wayne** [comment]
***Cancel button sends the user back to the profile page but the Save button has no functionality yet***

**Comment by Ali98Wayne** [comment]
Profile Page Template created (profile.html)

**Comment by Ali98Wayne** [comment]
"My Profile" Navigation Bar Link created

**Comment by Ali98Wayne** [comment]
***Read-Only Textareas created as placeholders, will be removed once database integration is finished***

**Comment by Ali98Wayne** [comment]
***Agency Location field will be split into Agency Zip Code, Address, State, & Phone Number. Is displayed as just "Agency Location" as a placeholder***

**Comment by Ali98Wayne** [comment]
***About Me field has been appropriately sized and has a character limit through HTML. This is a placeholder, character limit without HTML is being worked on to prevent attacks***

**Comment by Ali98Wayne** [comment]
***Contact Info is a placeholder, this will just be the Agency's email when we store this field in the database***

**Comment by Ali98Wayne** [comment]
Decided the Profile Icon should be displayed on the top-left of the screen, 1 of the 5 icons is currently displayed as a placeholder to get an ideea of where the picture will be.

**Comment by Ali98Wayne** [comment]
Added an Edit button to take Agencies to the Update Profile page.

**Comment by Ali98Wayne** [comment]
Cleaned up HTML/CSS Template Code, removed unnecessary declarations, merged 3 CSS files into 1, updated the htmlMockup folder with new changes.

**Comment by Ali98Wayne** [comment]
SQL Database has already been made, modifying profiles is something I am still figuring out. User should be taken to another page where they enter their username then be sent to the update profile page. Once the fields have been entered in the update profile page, they are taken back to their profile page.

**Comment by Ali98Wayne** [comment]
Changing profile page font, position, and added a white background to text except for the username because that breaks the page from my testing.

**Comment by Ali98Wayne** [comment]
Pushed profile.php, forgot to in the initial commit
